# environment.yml  – pinned builds that actually exist
name: steptohdf5
channels:
  - conda-forge
dependencies:
  # keep within the ABI umbrella that igl/pythonocc-core were built for
  - python=3.11          # py311 wheels exist for both libs
  - numpy>=1.24,<2       # avoid NumPy 2 until all deps catch up
  - mamba                # optional, but handy inside the env
  # CAD / geometry stacks (exact versions that exist today)
  - pythonocc-core=7.9.0=*novtk*
  # I/O & helpers
  - h5py
  - meshio
  - meshplot
  - joblib
  - tqdm
  - pip                  # pip will install your wheel in the next layer
