
package:
  name: "steptohdf5"
  version: "v0.1.1"

source:
  path: ..                # build from the root of your repo
  sha256: 2386a996fc851f40c27a8f652797cb5807e84f17090ef52b81f47a1d2f4ca3c8

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"   # pip inside conda-build is OK

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - pythonocc-core 7.4.0
    - igl
    - h5py
    - meshio
    - meshplot
    - joblib
    - tqdm

test:
  imports:
    - steptohdf5
  commands:
    - steptohdf5 --help

about:
  home: https://github.com/better-step/cadmesh
  license: GPL-3.0
  summary: "Convert STEP to HDF5 surface-mesh archives"

extra:
  recipe-maintainers:
    - itsmeechandu
